// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:ebbcdee7-548b-4e62-900c-164aa34f7439",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_To5M29zZE",
    "aws_user_pools_web_client_id": "4h9vq1c7s4o9gg2mptkctpfj8q",
    "aws_dynamodb_all_tables_region": "eu-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "konsultantprofile",
            "region": "eu-west-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "headlightapi",
            "endpoint": "https://afhu9fml17.execute-api.eu-west-1.amazonaws.com/Prod",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
